module

public import EffectSSA.ProofSketch.Pattern
public import EffectSSA.ProofSketch.Rewrite
public import EffectSSA.ProofSketch.EqnLemmaAttr
public import Lean.Elab.Tactic.Simp
public import Lean.Meta.LitValues
public meta import Lean.Meta.Tactic.Simp.Main
public meta import Lean.Meta.Tactic.Simp.Rewrite
public meta import Lean.Elab.Tactic.Basic

public section

/-!
# Proof Automation

This file defines some tactics and simprocs that make it easier to work
with the proof obligations generated by the framework; these are
predominantly used in the case study.

**AI DISCLOSURE**:
Large parts of this file have been vibe-coded,
including LLM-generated comments and doc-strings!
-/

/-!
## List.idxOf? Simplification

We register two simp-lemmas for the pattern:
  `List.idxOf? x [y, z, ...] = some $n`
Where the rhs is a constant
-/
section ListIdxOf

/-- Peel off a matching head. -/
@[simp, grind =]
theorem List.idxOf?_cons_eq_some_zero [BEq α] [LawfulBEq α] {a b : α} {xs : List α} :
    (b :: xs).idxOf? a = some 0 ↔ b = a := by
  simp [List.idxOf?_cons]

/-- Peel off a non-matching head. -/
@[simp, grind =]
theorem List.idxOf?_cons_eq_some_succ [BEq α] [LawfulBEq α] {a b : α} {xs : List α} {n : Nat} :
    (b :: xs).idxOf? a = some (n + 1) ↔ b ≠ a ∧ xs.idxOf? a = some n := by
  simp only [idxOf?_cons, beq_iff_eq, ne_eq]
  split <;> (simp; grind)

end ListIdxOf

namespace EffectSSA.ProofSketch
open Lean Meta Simp

/-!
## `Pattern` `getElem` Reduction

Simproc that reduces `(P : Pattern _ _)[k]` to a spelled-out chain of
`List.cons` / `InstSeq.cons` applications, whenever the index `k` is a concrete
natural number literal and the reduction succeeds under default transparency.
-/
section PatternGetElem

/--
Assuming that `e` is already in whnf, recursively reduce the rest of the spine
of the list (leaving each `cons`-head untouched).

`u` has to be be such that `e` is of type `List α` for some `α : Type u`;
this is passed in rather than re-computed since it remains constant for the
whole list.
-/
private meta partial def reduceInstSeqSpine (u : Level) (e : Expr) : MetaM Expr := do
  match_expr e with
  | List.cons α head tail =>
      let tail ← whnf tail
      let tail ← reduceInstSeqSpine u tail
      return mkApp3 (mkConst ``List.cons [u]) α head tail
  | _ => return e

/--
`dsimp`-procedure that rewrites `(P : Pattern _ _)[k]` — with `k` a concrete
`Nat` literal — into a spelled-out chain of `List.cons` / `InstSeq.cons`
applications, using default transparency.

If the initial reduction does not produce a `List.cons` or `List.nil`, the
expression is left untouched.  When it succeeds, the rest of the sequence is
reduced recursively, but each individual instruction (the `cons`-heads) is
left as-is.
-/
dsimproc reducePatternGetElem
    (@GetElem.getElem (EffectSSA.ProofSketch.Pattern _ _) Nat _ _ _ _ _ _) := fun e => do
  let_expr GetElem.getElem _ _ _ _ _ _ idx _ ← e | return .continue
  let some _ ← getNatValue? idx | return .continue
  let e ← withDefault <| whnf e
  match_expr e with
  | List.cons α _ _ =>
      let u ← getDecLevel α
      let e ← withDefault <| reduceInstSeqSpine u e
      return .done <| e
  | List.nil _ => return .done e
  | _ => return .continue

end PatternGetElem

/-!
## `MultiContext.Complete` of `InstSeq.toContext`

Simproc that matches `(InstSeq.toContext xs is).Complete`, whenever `xs`
is a list literal (as recognised by `getListLit?`),
and rewrites the goal along `InstSeq.complete_toContext_iff`.
The resulting `List.Pairwise (· ≠ ·) xs` and `∀ x ∈ xs, ∃ i ∈ is, i.results = x`
conjuncts are then simplified into the concrete conjunctions of dis-equalities
and per-element `∃`-goals.
-/
section CompleteToContext

/--
Combine two iff-shaped steps with `and_congr`, collapsing any `True`
conjunct via `true_and` / `and_true` so the resulting expression is free
of trivial `True`s.

Given `hl : L ↔ l` and `hr : R ↔ r`, returns `(t, h : L ∧ R ↔ t)` where
`t` is `l ∧ r` (or one of the two, or `True`, if either side is `True`).
-/
private meta def andCongrCollapseTrue
    (l r : Expr) (hl hr : Expr) : MetaM (Expr × Expr) := do
  let step ← mkAppM ``and_congr #[hl, hr]
  if l.isConstOf ``True && r.isConstOf ``True then
    let simp ← mkAppM ``Iff.of_eq #[← mkAppM ``and_true #[mkConst ``True]]
    return (mkConst ``True, ← mkAppM ``Iff.trans #[step, simp])
  else if l.isConstOf ``True then
    let simp ← mkAppM ``Iff.of_eq #[← mkAppM ``true_and #[r]]
    return (r, ← mkAppM ``Iff.trans #[step, simp])
  else if r.isConstOf ``True then
    let simp ← mkAppM ``Iff.of_eq #[← mkAppM ``and_true #[l]]
    return (l, ← mkAppM ``Iff.trans #[step, simp])
  else
    return (mkApp2 (mkConst ``And) l r, step)

/--
Given element type `α`, predicate `φ : α → Prop`, and elements
`[e₀, …, eₙ₋₁]`, produce `(t, h)` where:
* `t` is the right-nested conjunction of the `φ eᵢ`
  (or `True` when the list is empty),
* `h : (∀ x ∈ [e₀, …, eₙ₋₁], φ x) ↔ t`.
-/
private meta partial def buildForallMemIff
    (α φ : Expr) : List Expr → MetaM (Expr × Expr)
  | [] => do
    let prf ← mkAppOptM ``List.forall_mem_nil #[some α, some φ]
    return (mkConst ``True, ← mkAppM ``iff_true_intro #[prf])
  | [e] => do
    let iff ← mkAppOptM ``List.forall_mem_singleton #[some α, some φ, some e]
    return (φ.beta #[e], iff)
  | e :: es => do
    let esLit ← mkListLit α es
    let step ← mkAppOptM ``List.forall_mem_cons
      #[some α, some φ, some e, some esLit]
    let (tgtRest, iffRest) ← buildForallMemIff α φ es
    let φe := φ.beta #[e]
    let (t, andIff) ←
      andCongrCollapseTrue φe tgtRest (← mkAppM ``Iff.refl #[φe]) iffRest
    return (t, ← mkAppM ``Iff.trans #[step, andIff])

/--
Given element type `α`, relation `R : α → α → Prop`, and elements
`[e₀, …, eₙ₋₁]`, produce `(t, h)` where:
* `t` is the conjunction of the `R eᵢ eⱼ` for `i < j` (nested in the shape
  produced by iterating `List.pairwise_cons`; `True` when the list has
  fewer than two elements),
* `h : List.Pairwise R [e₀, …, eₙ₋₁] ↔ t`.
-/
private meta partial def buildPairwiseIff
    (α R : Expr) : List Expr → MetaM (Expr × Expr)
  | [] => do
    let prf ← mkAppOptM ``List.Pairwise.nil #[some α, some R]
    return (mkConst ``True, ← mkAppM ``iff_true_intro #[prf])
  | [e] => do
    let prf ← mkAppM ``List.pairwise_singleton #[R, e]
    return (mkConst ``True, ← mkAppM ``iff_true_intro #[prf])
  | e :: es => do
    let esLit ← mkListLit α es
    let step ← mkAppOptM ``List.pairwise_cons
      #[some α, some R, some e, some esLit]
    -- Head predicate is `R e : α → Prop`. Since `R` is a hard-coded
    -- (partial) constant application, no lambda is introduced.
    let (tgtHead, iffHead) ← buildForallMemIff α (mkApp R e) es
    let (tgtTail, iffTail) ← buildPairwiseIff α R es
    let (t, andIff) ← andCongrCollapseTrue tgtHead tgtTail iffHead iffTail
    return (t, ← mkAppM ``Iff.trans #[step, andIff])

/--
`simp`-procedure that fires on `(InstSeq.toContext xs is).Complete` whenever
`xs` is a concrete list literal.  It applies `InstSeq.complete_toContext_iff`
and then, using the elements returned by `getListLit?`, directly builds the
target expression and a proof term — no nested `simp` call is required.
-/
simproc reduceCompleteToContext
    (MultiContext.Complete (@InstSeq.toContext _ _ sorry _)) := fun e => do
  let_expr MultiContext.Complete _ _ ctx ← e | return .continue
  let ctx ← whnf ctx
  let_expr InstSeq.toContext _ xs _ is ← ctx | return .continue
  let some elts ← getListLit? xs | return .continue
  let elts := elts.toList
  -- Apply the top-level equivalence.
  let iffProof ← mkAppM ``InstSeq.complete_toContext_iff #[xs, is]
  let_expr Iff _ rhs ← ← inferType iffProof | return .continue
  let_expr And rhs₁ rhs₂ ← rhs | return .continue
  -- Recover the element type from the pairwise conjunct.  The relation
  -- there is `fun x1 x2 => x1 ≠ x2` — we hard-code it as `@Ne α` to avoid
  -- carrying an anonymous function into the target.
  let_expr List.Pairwise α _ _ ← rhs₁ | return .continue
  let u ← getLevel α
  let neRel := mkApp (mkConst ``Ne [u]) α
  -- Descend under the `∀ x` binder of the forall-mem conjunct to recover
  -- the predicate `x ↦ ∃ i ∈ is, i.results = x`.
  let existsPred ← withLocalDeclD `x α fun x => do
    let body ← whnf (← Meta.instantiateForall rhs₂ #[x])
    let some (_, φx) := body.arrow? | throwError
      "unexpected shape for forall-mem body:{indentExpr body}"
    mkLambdaFVars #[x] φx
  -- Directly build the pairwise and forall-mem targets and their proofs.
  let (pairTgt, pairIff) ← buildPairwiseIff α neRel elts
  let (existsTgt, existsIff) ← buildForallMemIff α existsPred elts
  let (finalTgt, andIff) ←
    andCongrCollapseTrue pairTgt existsTgt pairIff existsIff
  let combinedIff ← mkAppM ``Iff.trans #[iffProof, andIff]
  let eqProof ← mkAppM ``propext #[combinedIff]
  return .done { expr := finalTgt, proof? := some eqProof }

end CompleteToContext

/-!
## `EqnLemma` Reduction

The core reduction is done by four auto-firing `dsimproc`s that unfold the
`EqnLemma`-family of definitions whenever the principal argument reduces
(under default transparency) to a concrete constructor application.  They
fire in both hypothesis and goal positions during any `simp` call:

* `reduceEqnLemmaUpTo` fires on `Pattern.EqnLemmaUpTo I h ρ` when `I` reduces
  to `Vector.mk _ _`.
* `reducePatternEqnLemma` fires on `Pattern.EqnLemma I x ρ` under the same
  condition.
* `reduceInstEqnLemma` fires on `Inst.EqnLemma i x ρ` when `i` reduces to
  `Inst.mk _ _ _`.
* `reducePatternCollapse` unfolds `Pattern.collapse` on a concrete
  `Vector.mk`, so the resulting `Vector.foldl` can be simplified further.

`InstSeq.EqnLemma` is already handled by its existing `_cons` / `_nil` simp
lemmas.  The `imp_of_eq_symm` lemma below collapses the redundant symmetric
equality premise `(x = y → y = x → P)` down to `x = y → P` — a common
residual left by unfolding `Inst.EqnLemma` against a `LocalEnv.with`.

A `reduceEqnLemmaUpTo` **tactic** then wraps these simprocs into a single
call: it optionally accepts `at h`, and if it finds a `Pattern.WellFormed`
or `InstSeq.WellFormed` hypothesis in the local context it destructures the
resulting `noShadowing` into per-pair variable inequalities before invoking
`simp_all`.  With those inequalities available `simp_all` can eliminate the
`x = y → P` and `∀ a, is.UsesAt a x → …` residuals that would otherwise
require a `grind` follow-up.
-/
section EqnLemmaReduction

/--
Unfold the head definition of `e` if the argument at position `argFromEnd`
(0-indexed from the last argument) reduces — under default transparency — to
an application whose head symbol is `head`.  Returns `.continue` otherwise.
-/
private meta def unfoldIfArgHeadIs (head : Name) (argFromEnd : Nat) (e : Expr) :
    MetaM Simp.DStep := do
  let args := e.getAppArgs
  if h : args.size ≤ argFromEnd then return .continue
  else
    let arg ← withDefault <| whnf args[args.size - 1 - argFromEnd]
    unless arg.isAppOf head do return .continue
    let some e' ← withDefault <| unfoldDefinition? e | return .continue
    return .visit e'

/--
Simproc for `Pattern.EqnLemmaUpTo I h ρ`: unfold when `I` reduces to a
concrete vector literal.
-/
dsimproc reduceEqnLemmaUpTo (Pattern.EqnLemmaUpTo _ _ _) := fun e =>
  unfoldIfArgHeadIs ``Vector.mk 2 e

/--
Simproc for `Pattern.EqnLemma I x ρ`: unfold under the same condition.
-/
dsimproc reducePatternEqnLemma (Pattern.EqnLemma _ _ _) := fun e =>
  unfoldIfArgHeadIs ``Vector.mk 2 e

/--
Simproc for `Inst.EqnLemma i x ρ`: unfold when `i` reduces to a concrete
`Inst.mk`.
-/
dsimproc reduceInstEqnLemma (Inst.EqnLemma _ _ _) := fun e =>
  unfoldIfArgHeadIs ``Inst.mk 2 e

/--
Simproc for `Pattern.collapse I`: unfold when `I` reduces to a concrete
`Vector.mk` (so the resulting `Vector.foldl` can be further simplified by
`simp`).
-/
dsimproc reducePatternCollapse (Pattern.collapse _) := fun e =>
  unfoldIfArgHeadIs ``Vector.mk 0 e

/-!
### `eqn_lemma` simp-set contents

The four simprocs above plus every general-purpose lemma the
`reduceEqnLemmaUpTo` tactic relies on are bundled into the
`eqn_lemma` simp attribute (registered in
`EffectSSA.ProofSketch.EqnLemmaAttr`).  Downstream case studies attribute
their concrete rewrite / instruction lemmas to the same set so that a bare
`reduceEqnLemmaUpTo` invocation picks them all up.
-/

attribute [eqn_lemma]
  -- Simprocs from this file
  reduceEqnLemmaUpTo reducePatternEqnLemma reduceInstEqnLemma
  reducePatternCollapse
  -- Pattern
  Pattern.getElem_hole Pattern.getElem_ofVector Pattern.toVector_ofVector
  Pattern.mem_ofVector
  -- Vector
  Vector.getElem_mk Vector.foldl_mk Vector.mem_mk
  -- InstSeq
  InstSeq.args_cons InstSeq.args_nil
  InstSeq.mem_usesAt InstSeq.EqnLemma_cons InstSeq.EqnLemma_nil
  InstSeq.noShadowing_cons InstSeq.noShadowing_nil
  -- VarSet
  VarSet.empty_sdiff VarSet.union_empty
  VarSet.mem_insert VarSet.mem_singleton VarSet.not_mem_empty
  VarSet.singleton_disjoint_iff VarSet.disjoint_union VarSet.union_disjoint
  -- LocalEnv
  LocalEnv.get?_with
  -- List
  List.getElem_toArray List.getElem_cons_succ List.getElem_singleton
  List.mem_toArray List.mem_cons List.not_mem_nil
  List.size_toArray List.length_cons List.length_nil
  List.foldl_toArray' List.foldl_cons List.foldl_nil
  List.nil_append List.cons_append
  -- Nat / Option / propositional logic
  Nat.zero_add
  Option.pure_def Option.bind_eq_bind
  forall_eq_or_imp forall_eq forall_const
  and_true and_self or_false or_self
  ne_eq not_or true_and if_true
  and_assoc

/--
Collapse a redundant symmetric equality premise.  Unfolding
`Inst.EqnLemma (constOp y c₂) x ρ` produces implications of the shape
`x = y → y = x → P`, since the equality direction inside `LocalEnv.with`
is `y = x` while the membership check `x ∈ [y]` normalises to `x = y`.
-/
@[simp] theorem imp_of_eq_symm {α : Sort u} (a b : α) (P : Prop) :
    (a = b → b = a → P) ↔ (a = b → P) :=
  ⟨fun h hab => h hab hab.symm, fun h hab _ => h hab⟩

/-!
### `reduceEqnLemma` tactic

Shell that dispatches the above simprocs and additionally pulls
distinctness of the pattern's defined variables out of any
`Pattern.WellFormed _ _` / `InstSeq.WellFormed _ _` hypothesis it finds in
the local context — so residual `x = y → P` premises collapse.

Usage:
* `reduceEqnLemmaUpTo [defs...]` — reduce `EqnLemmaUpTo` in the goal.
* `reduceEqnLemmaUpTo [defs...] at h` — reduce `EqnLemmaUpTo` in `h`.

The list `[defs...]` accepts any extra `simp` lemmas / definitions to unfold
(typically the concrete rewrite, e.g. `constFoldRw`).
-/
section EqnLemmaUpToTactic
open Lean Elab Tactic Meta Parser.Tactic

/--
Search the local context for a hypothesis whose type reduces (under default
transparency) to a `Pattern.WellFormed _ _` or `InstSeq.WellFormed _ _`
application.  Returns the hypothesis's user-facing identifier.
-/
private meta def findWellFormedHyp : TacticM (Option Ident) := do
  for decl in ← getLCtx do
    if decl.isImplementationDetail then continue
    let ty ← withDefault <| whnf decl.type
    if ty.isAppOf ``Pattern.WellFormed || ty.isAppOf ``InstSeq.WellFormed then
      return some (mkIdent decl.userName)
  return none

/--
Convert an array of `term`s into an array of `simpLemma`s so they can be
spliced into a `simp [ … ]` call.
-/
private meta def toSimpLemmas (ts : Array (TSyntax `term)) :
    MacroM (TSyntaxArray `Lean.Parser.Tactic.simpLemma) :=
  ts.mapM fun t => `(Lean.Parser.Tactic.simpLemma| $t:term)

syntax (name := reduceEqnLemmaUpToTac)
  "reduceEqnLemmaUpTo" (ppSpace "[" term,* "]")? (location)? : tactic

elab_rules : tactic
  | `(tactic| reduceEqnLemmaUpTo $[[$args,*]]? $[$loc:location]?) => do
    let args := args.map (·.getElems) |>.getD #[]
    let simpArgs ← liftMacroM <| toSimpLemmas args
    -- If a well-formedness hypothesis is in context, extract its
    -- `noShadowing` field and reduce it to concrete disjointness /
    -- inequality facts, so downstream `simp_all` can eliminate `x = y → P`
    -- premises.
    if let some wf ← findWellFormedHyp then
      -- Extract `noShadowing`, reduce it to concrete pairwise inequalities,
      -- then flatten the resulting nested `And`s and destructure so each
      -- inequality becomes a first-class hypothesis.  `simp_all` will then
      -- pick these up and use them to rewrite `x = y` to `False`, collapsing
      -- the `x = y → P` residuals in the goal.
      evalTactic <| ← `(tactic| have wf_noShad := ($wf).noShadowing)
      evalTactic <|
        ← `(tactic| try simp only [eqn_lemma, $simpArgs,*] at wf_noShad)
      -- Peel off conjuncts one layer at a time.  Since `and_assoc` is in
      -- `eqn_lemma`, the residual is right-nested, so a simple
      -- `repeat` loop covers arbitrary pattern sizes.
      evalTactic <| ← `(tactic| try (
        repeat (obtain ⟨_, wf_noShad⟩ := wf_noShad)))
    -- Main simplification: `simp_all only` restricted to the
    -- `eqn_lemma` simp set (auto-firing simprocs + general-purpose
    -- unfolding lemmas + any case-study lemmas attributed downstream) plus
    -- the user's extra hints.
    evalTactic <| ← `(tactic| simp_all only [eqn_lemma, $simpArgs,*])

end EqnLemmaUpToTactic

end EqnLemmaReduction

end EffectSSA.ProofSketch
